### ISSUE TITLE
Clean the Label Chaos

### ISSUE THREAD

**Issue by molnard** [molnard/WalletWasabi#63]
**📜 Preamble**

Clean the Label Chaos by @molnard 

**📖 TL;DR - Too Long, Didn't Read**

The labeling system is an essential element of privacy in Wasabi. Coin selectors are basing selection on them or users when manual selection is done. It must work perfectly. Currently, it works more or less but it is like a wild octopus, grabbing information from here and there - nobody dares to touch it and fix current issues. The idea is to have a separate module just for labels, plus unit tests. 

**🌟 Specification, Scope, and Features**

- Refactoring the label system by removing it from SmartCoin and storing it in a separate module. 
- The module will be optimized for speed and memory usage. 
- The module should be designed in a wallet-independent manner since we have cross wallet label system.
- Keep in mind label exporting as a feature in the future. 

**⚔️ Motivation**

As I mentioned earlier, the labeling system is an essential element. It should work perfectly and be easily maintainable. Currently, it has a few issues that nobody dares to touch - because it might break other things. A lot of time and resources are spent on this because every time there is an issue, it is very hard to understand how it actually works. 

- Stucked issues.
- Not maintainable. 

**📜 Rationale**

The rationale behind this is not the solidest one. However, if we think about dev time spent on label issues and the effectiveness of fixing them perfectly is calling attention. It is not possible to shoot down issues one by one because the underlying business logic is flawed. So we can go all-in or don't touch it at all. 

**🌌 Backward Compatibility**

Yes, it will be an essential part of migrating old labels to the new system in a safe way. We have to make sure to not loose any label. This is important. 

**📚 Reference Implementation (optional)**

- https://github.com/zkSNACKs/WalletWasabi/issues/10193
- https://github.com/zkSNACKs/WalletWasabi/issues/10980
- https://github.com/zkSNACKs/WalletWasabi/issues/11436
- https://github.com/zkSNACKs/WalletWasabi/issues/11038
- https://github.com/zkSNACKs/WalletWasabi/issues/11153
- https://github.com/zkSNACKs/WalletWasabi/issues/11241
- https://github.com/zkSNACKs/WalletWasabi/issues/11313
- https://github.com/zkSNACKs/WalletWasabi/issues/8080
- https://github.com/zkSNACKs/WalletWasabi/issues/9806
- https://github.com/zkSNACKs/WalletWasabi/issues/6056

**🧑‍🏫 Team involvements**

Lead: ?
Code team. 

**💪  Subtasks**

The goal of the refactor is to free up SmartTransaction and SmartCoin from all the label-related data objects and move them into one place called LabelManager. That is it. We agreed with Lucas that the current concept is flawed but refactoring would lead to refactoring the whole transaction processing which is out of the scope of this Quest! 

🕐 Overall time estimation: 8 weeks

⛔ What NOT to do
- Create a database or a file for LabelManager, use only memory. 
- Remove information from files. Do not change the structure of the wallet file or transactions.dat.
- Try to make the solution more robust against reorg and RBF. The same behavior that we have now is OK.
- Thinking about any more recursive generation of total labels or anything like that. That would lead very far. It is enough to gather all the logic into LabelManager as a first step. 

✅ Todo:
- [ ] Create a class called LabelManager PoC
  - Fill up LabelManager with the data the same way we do now with SmartCoin and SmartTransaction labels. Yes, it will be a duplication for now.   
  - Store stuff in memory only (with the consideration of later it will be a database).
  - The data in LabelManager should look like a list of [PubKey, LabelArray, Wallet] There might be one or more labels or no labels at all. Similarly what you can see in the wallet file.
  - The public API of the class is like:  "Give me the labels for this Pubkey".
  - Make sure that new information is processed as well, when we receive a new tx it should be processed in this LabelManager as well. For example, when I get a tx, the created coins will inherit the labels from the spent coins, etc. 
  - Make sure to take care that the SmartTransaction itself can have labels as well. Check the Transactions.dat file. 
- [ ] Remove all label-related stuff from SmartCoin and move into LabelManager. All the places where it has been referenced, now have to use LabelManager to get the information.
- [ ] Remove all label-related stuff from SmartTransaction and move into LabelManager. All the places where it has been referenced, now have to use LabelManager to get the information.
- [ ] Integrate Cluster calculation into LabelManager and remove Cluster class from HdPubKey class. 
- [ ] Make sure that AnonScore is incorporated.
- [ ] Make sure that all the Label, Cluster, and related information is coming from LabelManager only.
- [ ] If it is working and makes sense try to add a few Unit Tests. 
- [ ] If the concept makes sense and everyone likes it try to break down the PoC if required and create the final PR.
